// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuFmTtMVmC4TeizWo0aVbBKG_jDTfw6s4',
    appId: '1:306779243372:web:67409598acf6436e906949',
    messagingSenderId: '306779243372',
    projectId: 'dollartab-b4368',
    authDomain: 'dollartab-b4368.firebaseapp.com',
    storageBucket: 'dollartab-b4368.appspot.com',
    measurementId: 'G-WPJX27WYEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAHaaN05bjslzKncPGt557c760WFgTKNU',
    appId: '1:306779243372:android:405ede64be1c80c2906949',
    messagingSenderId: '306779243372',
    projectId: 'dollartab-b4368',
    storageBucket: 'dollartab-b4368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLz586qIb_WZAONcNIN0aTMNLXV3p8Vuw',
    appId: '1:306779243372:ios:5b485a6afe932b0e906949',
    messagingSenderId: '306779243372',
    projectId: 'dollartab-b4368',
    storageBucket: 'dollartab-b4368.appspot.com',
    iosClientId: '306779243372-3uff3v2scp8l463klmpt5264ne96da05.apps.googleusercontent.com',
    iosBundleId: 'com.dollartab.userdollartab',
  );
}
